### ISSUE TITLE
Getting error "You need ASDF >= 3.1 to load this system correctly" while running make-binary.sh

### ISSUE THREAD

**Issue by amittendulkar** [lokedhs/gnus-outlook-style#10]
After applying the patch as mentioned in the document (`patch -p1 < /path/to/gnus-outlook-style/closure-html.diff`) I got the following errors. What seems to be wrong?

```
amit@myhost:~/packages/gnus-outlook-style/format-html-email$ ./make-binary.sh 
This is SBCL 1.1.14.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "format-html-email":
  Load 1 ASDF system:
    format-html-email
; Loading "format-html-email"
;;; Checking for wide character support... WARNING: Lisp implementation doesn't use UTF-16, but accepts surrogate code points.
 yes, using code points.
..
debugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR in thread #<THREAD "main thread" RUNNING {1002A8B8B3}>: Error while trying to load definition for system bordeaux-threads from pathname /home/amit/quicklisp/dists/quicklisp/software/bordeaux-threads-v0.8.5/bordeaux-threads.asd: READ error during COMPILE-FILE: You need ASDF >= 3.1 to load this system correctly.(in form starting at line: 1, column: 0, file-position: 0)

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT                                 ] Abort loading file "/home/amit/quicklisp/dists/quicklisp/software/bordeaux-threads-v0.8.5/bordeaux-threads.asd".
  1: [REINITIALIZE-SOURCE-REGISTRY-AND-RETRY] Retry finding system bordeaux-threads after reinitializing the source-registry.
  2:                                          Give up on "temporary-file"
  3:                                          Give up on "format-html-email"
  4: [CONTINUE                              ] Ignore runtime option --eval "(progn (ql:quickload \"format-html-email\") (save-lisp-and-die \"format_quoted_mail\" :toplevel (find-symbol \"MAIN\" \"FORMAT-HTML-EMAIL\") :executable t))".
  5:                                          Skip rest of --eval and --load options.
  6:                                          Skip to toplevel READ/EVAL/PRINT loop.
  7: [EXIT                                  ] Exit SBCL (calling #'EXIT, killing the process).

((FLET #:LAMBDA10577 :IN ASDF/FIND-SYSTEM:LOAD-ASD) #<SB-C::INPUT-ERROR-IN-COMPILE-FILE {1005C7B3F3}>)
0] 
```

I am using Ubuntu 14.04.

**Comment by lokedhs** [comment]
What version of SBCL are you using?

**Comment by amittendulkar** [comment]
I get the following output for `--version` argument,
```
SBCL 1.1.14.debian
```

**Comment by lokedhs** [comment]
That is a very old version of SBCL. The Debian releases are famously
outdated. Please update to the latest version by downloading it from the
SBCL site and try again.

**Comment by amittendulkar** [comment]
Thanks. I tried to update to the latest version but I am confused now. Even after installing the latest version I see the same old version displayed in the `--version` output (`SBCL 1.1.14.debian`).

I installed from sbcl-1.3.4-source.tar (followed steps in INSTALL) and `sbcl` got installed in `/usr/local/bin` (`ls -l` shows the updated timestamp for the sbcl file). `which sbcl` is pointing to `/usr/local/bin/sbcl`. I am not sure what I am doing wrong here.

**Comment by lokedhs** [comment]
Bash probably sees the old version from the cache. Try typing `hash -t` in the shell to refresh the cache.

You should also uninstall the old version from the repository. Other things may decide use the wrong version.

**Comment by amittendulkar** [comment]
Thanks, using new shell did the trick. I bumped into following error after running `make-binary.sh`. It seems I am getting blocked as I am behind a corporate proxy. However, I have already installed cntlm proxy and commands like 'sudo apt-get update' are working fine through the same shell. Do I have to do something extra to avoid the error? Else I will try the workaround of running the script outside of the corporate firewall.
```
To load "format-html-email":
  Load 1 ASDF system:
    format-html-email
; Loading "format-html-email"
;;; Checking for wide character support.... WARNING: Lisp implementation doesn't use UTF-16, but accepts surrogate code points.
 yes, using code points.
;;; Building Closure with CHARACTER RUNES
;;; Checking for wide character support... WARNING: Lisp implementation doesn't use UTF-16, but accepts surrogate code points.
 yes, using code points.
..To load "temporary-file":
  Load 4 ASDF systems:
    alexandria bordeaux-threads cl-fad cl-ppcre
  Install 2 Quicklisp releases:
    temporary-file unit-test

debugger invoked on a QL-HTTP:UNEXPECTED-HTTP-STATUS in thread
#<THREAD "main thread" RUNNING {1002946C63}>:
  Unexpected HTTP status for #<URL
                               "http://beta.quicklisp.org/archive/unit-test/2012-05-20/unit-test-20120520-git.tgz">: 403

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT   ] Give up on "temporary-file"
  1:            Give up on "format-html-email"
  2: [CONTINUE] Ignore runtime option --eval "(progn (ql:quickload \"format-html-email\") (save-lisp-and-die \"format_quoted_mail\" :toplevel (find-symbol \"MAIN\" \"FORMAT-HTML-EMAIL\") :executable t))".
  3:            Skip rest of --eval and --load options.
  4:            Skip to toplevel READ/EVAL/PRINT loop.
  5: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).

((LAMBDA (QL-HTTP::CONNECTION) :IN QL-HTTP:HTTP-FETCH) #<SB-SYS:FD-STREAM for "socket 10.44.21.25:38490, peer: 54.230.190.198:80" {1003B5EF43}>)
```

**Comment by lokedhs** [comment]
The Quicklisp FAQ explains how to use it with a proxy: https://www.quicklisp.org/beta/faq.html

**Comment by amittendulkar** [comment]
After setting the proxy, the script stuck at the download step for a long time. So I went  ahead with the workaround and got the `format_quoted_mail` compiled by running the script outside of the proxy. I copied it to `~/bin`.

I entered the below lines in ~/.emacs,d/init.el towards the end and restarted Emacs and Gnus. When I pressed `S W` (wide reply) I saw the message buffer with the standard quoted text (i.e. previous email lines beginning with >). What might be wrong?

```
(add-to-list 'load-path "~/packages/gnus-outlook-style")  ;; this is where I had copied gnus outlook style initially
(setq outlook-style-format-helper-location "~/bin/format_quoted_mail")
(require 'outlook-style)
```

**Comment by lokedhs** [comment]
The mode injects itself in the normal followup command ("F" from the gnus-summary list).

I have to admit that I don't know what wide reply does that followup does not, so I never bothered to add the instrumentation to the former.

**Comment by lokedhs** [comment]
You probably also want to check that the generated binary works. There may be issues when copying them between systems.

**Comment by amittendulkar** [comment]
I think the binary is working.
```
$ format_quoted_mail 
An unhandled error condition has been signalled:
   Usage: content old-content image-directory styles-file
```
I will check the gnus follow up functionality.

**Comment by amittendulkar** [comment]
Since I am using cloned .emacs.d folder, F might be mapped to another function. Because after pressing "F" still I am getting the buffer named "*unsent wide reply to <email>*" (is it the same buffer name for follow up command?). I tried with `M-x gnus-article-followup-with-original`. In both cases I am seeing the traditional citation (> marks).

**Comment by lokedhs** [comment]
Please try typing `C-h f gnus-summary-followup-with-original`. In the help buffer that is displayed, you should see the following line: `:around advice: ‘ad-Advice-gnus-summary-followup-with-original’`.

Please check if this happens.

**Comment by amittendulkar** [comment]
All I am getting is the following (without ad-Advice),

```
gnus-summary-followup-with-original is an interactive compiled Lisp
function.

(gnus-summary-followup-with-original N &optional FORCE-NEWS)

Compose a followup to an article and include the original article.
The text in the region will be yanked.  If the region isn't
active, the entire article will be yanked.
```
Any tips where I should look for?

**Comment by lokedhs** [comment]
It seems like the file isn't loaded at all. What happens if you run
(require 'outlook-style) manually?

**Comment by amittendulkar** [comment]
I did M-: and typed `(require 'outlook-style)`

I checked *Messages* buffer and saw the following,
```
eval-buffer: Cannot open load file: muse-publish
```

**Comment by lokedhs** [comment]
Please install muse from Elpa and try again.

**Comment by amittendulkar** [comment]
Yes, I was able to send blended email after installing muse. It preserved all the earlier formatting. Thanks for providing extensive help. I noticed that when I inserted a (org) table in the message and used M-x org-mime-htmlize. The first line in the email showed the below text which usually wasn't not visible in HTML email earlier,

```
< type=alternative><#!part type=text/plain>#+OPTIONS: latex:t 
```

**Comment by amittendulkar** [comment]
I guess I don't have to use `M-x org-mime-htmlize` at all. The added table is automatically htmlized.

**Comment by lokedhs** [comment]
Yes, it uses muse for that: https://www.gnu.org/software/emacs-muse/manual/

People have asked me to add Org mode formatting as well, but I haven't
looked into that yet.

**Comment by amittendulkar** [comment]
I noticed that the send email buffer remain open after sending emails. Is this intentional?

**Comment by lokedhs** [comment]
Yes, it's intentional. It's sometimes useful to see the output from the
program.
